### ISSUE TITLE
KICKED FOR : BOOK TO BIG

### ISSUE THREAD

**Issue by sysysysy242** [fr1kin/ForgeHax#228]
I active my forgehax bookbot , and i get kick for : 
BOOK TO BIG

How to fix that ?

**Comment by fr1kin** [comment]
I need more details

**Comment by VADemon** [comment]
Try these commands on the server:

* /version
* /spigot
* /paper

You will probably have no access to the first two, and the third one can either say it doesn't exist or fail due to permission and the difference is significant. Because it could either be a plugin or Paper's broken patch.

The Paper patch is broken in so far that it also breaks writing perfectly legitimate books as soon as you write enough letters to trigger their variable threshold. There could also be a separate plugin, but it doesn't matter.

You can't fix any of that and if you have to ask this, stop trying anything else to not waste more time.

/closed
