### ISSUE TITLE
My text file have problem loading into books

### ISSUE THREAD

**Issue by ShironNorihs** [fr1kin/ForgeHax#230]
I am using forgehax 1.12 and when i try to start book bot with that file
[File.txt](https://github.com/fr1kin/ForgeHax/files/4898290/File.txt)
its filling one book and then says it finished.

**Comment by VADemon** [comment]
Do you have more unwritten books in your hotbar?

**Comment by ShironNorihs** [comment]
yes

**Comment by ShironNorihs** [comment]
And with diffrent file it works

**Comment by VADemon** [comment]
Please don't flood with your messages on Github like that because each message = 1 notification (for example email).

Your input file (book) is read correctly, as far as it can. The BookBot GUI shows `P/T=0/40 and B/T=0/1` (Pages/Total and Books/Total) when you load the file. That's max 40 pages and thats what you get.

The problem with your file: it's ~28KB but only 10k code points (and some of them are invalid). As per wiki, a 50-page book can store up to 12.5k letters. Thats where you get 40 out of 50 pages. Though the first and last characters appear correctly in both notepad and in-game. I don't think anything is actually lost.

**Fill up the file further if you want more text to be written.**

If you want my original file (doesn't bypass the hopper plugin, because I smart-assed too much on that one), it's below. It probably won't work whereever you wanna try, but have fun.
[randombook.txt](https://github.com/fr1kin/ForgeHax/files/4898420/randombook.txt) (2018-10-01 04:04)

/closed

**Comment by ShironNorihs** [comment]
Thanks ^w^
