### ISSUE TITLE
Wrong tracers for objects behind the player

### ISSUE THREAD

**Issue by isgulkov** [fr1kin/ForgeHax#244]
So, on this screenshot, tracers correctly point at the objects in front of me:

![](https://i.imgur.com/sFih5Ie.png)

But if I turn around, the tracers **incorrectly** point to non-existent mirror images of the targets. They are mirrored across the position of my eyes (i.e. a point):

![](https://i.imgur.com/KXZrZhj.png)

> I enabled ESP just to show that ESP works correctly here. Tracers work like this with or without it.

This is confusing and misleading. With a lot of objects around, these tracers are practically useless.

When done right, the lines pointing behind the player should go off the edge of the screen, like this:

![](https://i.imgur.com/H7p0WUL.png)

---

I just checked this on `ForgeHax-1.16.2-3.1.0-4f9219db` (latest as of now), but Forge is `1.16.2-33.0.21` — none of the later versions work for me so far (they hang while stitching the `blocks.png` atlas — with empty `mods` folder).

Evidently, part of the reason this happens is that the lines are not clipped with the near plane of the viewing frustrum, as they should be. Understandable mistake. This, however, does not explain the top-bottom mirroring of the positions.

My experience with Forge mods is fairly limited, but I could look into this myself if this is indeed a ForgeHax bug. Reply here if you'd be fine with accepting my PR.

**Comment by fr1kin** [comment]
A big issue with the tracers is the fact they are draw in 2D space instead of 3D space. Originally my tracers had just arrows on the sides on your screen pointing in the direction of an entity. Somebody made a PR with a line mode. I didn't really care it wasn't done properly because I don't use it, so if you want to correct that feel free to.

Another issue is that the world coordinate to screen coordinate transformation uses a magic value instead of the near plane to determine if a coordinate is visible on screen or not, which can result in some funky behavior.

>I just checked this on ForgeHax-1.16.2-3.1.0-4f9219db (latest as of now), but Forge is 1.16.2-33.0.21 — none of the later versions work for me so far (they hang while stitching the blocks.png atlas — with empty mods folder).

I'll fix this right now. It appears Forge can't go a week without making breaking changes 🙄

>This, however, does not explain the top-bottom mirroring of the positions.

I'll look into this

**Comment by fr1kin** [comment]
>I'll fix this right now. It appears Forge can't go a week without making breaking changes roll_eyes

I updated to latest forge and everything seems fine? Both in and outside IDE appear to be working fine

**Comment by fr1kin** [comment]
Should be fixed now. Probably should be doing the lines in 3D space, but I am not really concerned about that.
