### ISSUE TITLE
Game crashes just before title screen.

### ISSUE THREAD

**Issue by Darkrym** [fr1kin/ForgeHax#299]
Game loads mods correctly but as it goes to load the start screen (I think anyway) it crashes. 

I'll attach the crash log in a paste bin as its quite long ([Here ](https://pastebin.com/ezz7zv6G))

I am using quite a big modpack (SevTech: Ages 3.2.1) with around 250 mod, running minecraft 1.12.2, forgehax 2.9.0 and forge 14.23.5.2855 (as well as the last 4 recent version of forge). I assume its some other mod messing with it, but without knowing much about minecraft crash logs it looks like it to do with how minecraft processes chunks.

**Comment by fr1kin** [comment]
Sadly looks like another crash caused by the markers patch in RenderChunk. If you comment out [this](https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/asm/ForgeHaxTransformer.java#L63) line and build, it should work. I don't plan on updating that version of 1.12.2 any more, but I will probably backport 1.16.4+ when I feel my code is modular enough.

**Comment by Darkrym** [comment]
Thanks, not much experience with java so been messing around in Intellij and gradle all arvo. No clue what I am doing yet so haven't gotten it to spit out a jar file yet tho.

**Comment by Darkrym** [comment]
Yeah I got that first part, I was using gradew build and it would fail. I'll try with the setupdecompworkspace next time I have a chance
